### PR TITLE
Made the logo for PSLab ,hope you like it

### PR DESCRIPTION
**Pull request by stealthanthrax**
Have added the logo in the folder and am also attaching it in the comments.
I hope you like it .

### CODE REVIEW

**Comment by stealthanthrax** [comment]
pslab

**Comment by stealthanthrax** [comment]
@mariobehling please let me know about the reviews

**Comment by mariobehling** [comment]
Thank you. Good start. We don't have a tagline. So there should not be any tagline on the logo. Would be good if the logo symbolizes a lab. So, probably take out the book and the tagline.

**Comment by stealthanthrax** [comment]
@mariobehling, I have a few ideas: expect another logo within 2-3 days

**Comment by stealthanthrax** [comment]
jjj
@mariobehling ,Pardon me for the delay,I was ill so couldn't complete another logo on time but I have made another logo,please me know about the reviews 😄

**Comment by stealthanthrax** [comment]
@mariobehling ,now the microscope depicts the word "lab" as you suggested.

**Comment by mariobehling** [comment]
Hi, thanks for the suggestions. We need something much cooler, that follow standard design procedures more closely, e.g. also works in two color mode. I am not able to go into all details here within an issue itself, but I hope we can follow up and engage people in Open Source Design. Therefore closing it.

**Pull request closed without merging**
