### PR TITLE
[WIP] Initial Commit for Packaging Box

### PR DESCRIPTION
**Pull request by cweitat**
image

### CODE REVIEW

**Comment by cweitat** [comment]
Comments please

**Comment by CloudyPadmal** [comment]
Are we putting extended edges to apply glue around the corners?

**Comment by cweitat** [comment]
@CloudyPadmal there are some more folded parts that are not shown in the drawing. The SVG only shows the part that is going to get printed

**Comment by CloudyPadmal** [comment]
I like this design! Can we put Fdroid as well?

**Pull request merged**
